name: wechat_push
on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies
      run: |
        npm install
    - name: Run JavaScript script
      run: |
        node index.js
